[package]
name = "remap-derive"
version = "0.1.0"
authors = ["tuztu <tuztucode@gmail.com>"]
edition = "2018"

[lib]
name = "remap_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
syn = "1.0.60"
quote = "1.0.9"
